/* 筠玲易數｜全站左側工作快捷列 */
(function () {
  'use strict';
  if (document.getElementById('jl-quick-nav')) return;
  var items=[{label:'功能首頁',mark:'首',href:'index.html'},{label:'四柱八字',mark:'柱',route:'四柱'},{label:'紫微九宮',mark:'宮',route:'九宮'},{label:'奇門遁甲',mark:'奇',route:'奇門'},{label:'數字八字卦',mark:'卦',route:'六親'},{label:'八星磁場',mark:'星',href:'bxcc.html'},{label:'流年運勢',mark:'運',route:'流年'},{label:'擇吉看日',mark:'日',href:'rz.html'},{label:'桃花神數',mark:'桃',href:'taohua.html'}];
  var style=document.createElement('style');style.id='jl-quick-nav-style';style.textContent='#jl-quick-nav{position:fixed;left:max(7px,env(safe-area-inset-left));top:50%;z-index:9500;transform:translateY(-50%);display:flex;flex-direction:column;gap:6px;padding:8px 6px;border:1px solid #e1bd5f;border-radius:999px;background:linear-gradient(180deg,#33043eea,#681078ed);box-shadow:0 12px 30px #2b023a55;backdrop-filter:blur(12px)}#jl-quick-nav a,#jl-quick-nav button{position:relative;width:40px;height:40px;display:grid;place-items:center;padding:0;border:1px solid #e4c56788;border-radius:50%;color:#f3dda0;background:#ffffff0d;text-decoration:none;font:900 14px serif}#jl-quick-nav span{position:absolute;left:49px;width:max-content;padding:7px 10px;border:1px solid #e2c362;border-radius:999px;color:#f5dfa0;background:#3c0448f2;font:800 11px sans-serif;opacity:0;visibility:hidden}#jl-quick-nav a:hover span,#jl-quick-nav button:hover span{opacity:1;visibility:visible}#jl-quick-toggle{display:none!important}@media(max-width:760px){#jl-quick-nav{left:4px;gap:4px;padding:7px 5px}#jl-quick-nav a,#jl-quick-nav button{width:36px;height:36px;font-size:12px}#jl-quick-toggle{position:absolute!important;right:-28px;top:50%;display:grid!important;width:23px!important;height:42px!important;transform:translateY(-50%)!important;border:1px solid #dfbe61!important;border-left:0!important;border-radius:0 999px 999px 0!important;color:#f6dda0!important;background:#5d0b6d!important}#jl-quick-nav.jl-collapsed{transform:translate(calc(-100% - 5px),-50%)}}';document.head.appendChild(style);
  var nav=document.createElement('nav');nav.id='jl-quick-nav';var toggle=document.createElement('button');toggle.id='jl-quick-toggle';toggle.type='button';toggle.textContent='›';nav.appendChild(toggle);if(matchMedia('(max-width:760px)').matches)nav.classList.add('jl-collapsed');toggle.onclick=function(){nav.classList.toggle('jl-collapsed')};items.forEach(function(item){var n=item.route?document.createElement('button'):document.createElement('a');if(item.route){n.type='button';n.onclick=function(){if(typeof window.jlOpenFeature==='function')window.jlOpenFeature(item.route);else location.href='index.html?route='+encodeURIComponent(item.route)}}else n.href=item.href;n.innerHTML=item.mark+'<span>'+item.label+'</span>';nav.appendChild(n)});document.body.appendChild(nav);
})();

/* 天衡｜四大命書：免費完整閱讀版 */
(function(){'use strict';if(!/\/index\.html$|\/$/.test(location.pathname)||document.getElementById('th-life-books'))return;
var books={love:{icon:'緣',title:'感情命書',score:'情感節奏 78',trend:'近期宜慢不宜急',summary:'你的感情課題不只是遇見誰，而是如何辨認真正穩定、願意投入的關係。近期先觀察互動是否持續，再決定投入程度。',now:'30日｜適合整理舊情緒與關係界線；新認識的人先看行動一致性。\n90日｜社交與互動機會逐步增加，主動表達比猜測對方更有利。',good:'優勢｜重感受、願意照顧關係，也能察覺細節。',watch:'留意｜避免因一時熱度過度投入，或把沒有說出口的期待當成對方應該知道。',action:'行動建議｜重要關係用一次清楚、溫和的對話確認彼此期待；單身者增加真實社交情境，不只停留在線上互動。'},career:{icon:'業',title:'事業命書',score:'事業節奏 82',trend:'先聚焦，再擴張',summary:'近期事業重點在把能力變成看得見的成果。與其同時開很多方向，更適合先完成一個能累積口碑、作品或收入的核心項目。',now:'30日｜適合收斂任務、整理流程、補足最影響成果的能力。\n90日｜合作、轉職或新專案機會增加，但條件要看長期成長與實際回報。',good:'優勢｜執行力與應變能力可成為突破點，適合把複雜問題拆成具體步驟。',watch:'留意｜不要因短期焦慮頻繁換方向，也別只看職稱而忽略工作內容與現金流。',action:'行動建議｜選一個90天可量化目標，每週追蹤成果；遇到合作先談清楚權責、報酬與交付標準。'},health:{icon:'養',title:'健康命書',score:'調候節奏 74',trend:'規律比補救重要',summary:'健康命書以生活節奏與五行調候作自我整理，不判斷疾病。近期更值得注意的是睡眠、壓力與活動量是否長期失衡。',now:'30日｜先固定睡眠與用餐時間，減少連續熬夜後再集中補眠。\n90日｜建立能長期維持的活動習慣，比短期高強度更重要。',good:'優勢｜一旦建立固定節奏，通常較容易持續。',watch:'留意｜疲勞、疼痛或其他持續不適不能用命理解釋或延誤就醫。',action:'生活建議｜從睡眠、飲食、活動、壓力四項各選一個小改變。若有健康疑慮，請依合格醫療專業評估。'},wealth:{icon:'財',title:'財富命書',score:'財務節奏 80',trend:'先守現金流，再求放大',summary:'財富不只看進帳，也看能否留下來。近期比追逐快速機會更重要的是建立穩定收入來源與可承受的風險界線。',now:'30日｜盤點固定支出、負債與真正能帶來收入的項目。\n90日｜可測試第二收入來源，但先小規模驗證，不宜一次投入過多資源。',good:'優勢｜當目標清楚時，較能把資源集中到有效項目。',watch:'留意｜避免因短期高報酬敘事忽略風險，也不要用借貸放大自己無法承受的部位。',action:'行動建議｜先建立緊急預備與現金流紀律，再談擴張；重大投資仍應依實際資料與專業意見判斷。'}};
var host=document.querySelector('.wrap')||document.body,sec=document.createElement('section');sec.id='th-life-books';sec.innerHTML='<div class="th-book-head"><small>TIANHENG · LIFE GUIDANCE</small><h2>四大命書</h2><p>感情・事業・健康・財富｜目前完整免費開放</p></div><div class="th-book-grid">'+Object.keys(books).map(function(k){var b=books[k];return '<article><b>'+b.icon+'</b><h3>'+b.title+'</h3><div class="th-score">'+b.score+'</div><p>'+b.trend+'</p><button data-book="'+k+'">閱讀完整命書</button></article>'}).join('')+'</div><div id="th-book-reading" hidden></div><div class="th-book-foot">目前不收 NT$99・隨喜支持照常保留<br><a href="https://line.me/R/ti/p/@788ldzke" rel="noopener">LINE｜三寶爸的命理分析 @788ldzke</a></div>';
var css=document.createElement('style');css.textContent='#th-life-books{margin:28px 0;padding:26px 18px;border:1px solid #cdbb91;background:linear-gradient(145deg,#fffdf8,#f3ead8);box-shadow:0 14px 40px #50350e14}.th-book-head{text-align:center}.th-book-head small{color:#9b762f;letter-spacing:.18em;font-size:10px}.th-book-head h2{margin:8px 0 7px;font-size:25px}.th-book-head p{color:#716354}.th-book-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.th-book-grid article{padding:18px 14px;border:1px solid #ddcfb0;background:#fffefa;text-align:center}.th-book-grid article>b{display:grid;place-items:center;width:44px;height:44px;margin:auto;border:1px solid #b18a3d;border-radius:50%;color:#8a2323;font:700 20px serif}.th-book-grid h3{margin:9px 0 4px;color:#4b3525}.th-score{font-size:11px;color:#a1782f;letter-spacing:.08em}.th-book-grid p{margin:7px 0 12px;color:#75695e;font-size:13px}.th-book-grid button{width:100%;padding:11px;border:0;background:#7d1d1d;color:#fff;font-weight:700}.th-book-foot{text-align:center;margin-top:18px;color:#7b6d60;font-size:12px;line-height:2}.th-book-foot a{display:inline-block;margin-top:6px;padding:10px 15px;border:1px solid #9d7b3c;color:#6f5120;text-decoration:none}#th-book-reading{margin-top:16px;padding:20px;border:1px solid #ddcfb0;border-left:4px solid #8a2323;background:#fffefa;color:#55483d;line-height:1.9}#th-book-reading h3{margin:0 0 4px;font:700 22px serif;color:#4b3525}#th-book-reading .lead{font-weight:700;color:#8a2323}#th-book-reading .block{margin-top:14px;padding-top:12px;border-top:1px solid #e6dcc8;white-space:pre-line}@media(max-width:430px){.th-book-grid{grid-template-columns:1fr}}';document.head.appendChild(css);host.appendChild(sec);
sec.onclick=function(e){var btn=e.target.closest('[data-book]');if(!btn)return;var b=books[btn.dataset.book],r=document.getElementById('th-book-reading');r.innerHTML='<h3>'+b.title+'</h3><div class="lead">'+b.score+'｜'+b.trend+'</div><div class="block">'+b.summary+'</div><div class="block">'+b.now+'</div><div class="block">'+b.good+'</div><div class="block">'+b.watch+'</div><div class="block">'+b.action+'</div>';r.hidden=false;r.scrollIntoView({behavior:'smooth',block:'start'})};
})();
